services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  service_order:
    build: ./service_order
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq

  service_payment:
    build: ./service_payment
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq